# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: '50 8-18 * * 1-6'
  watch:
    types: [started]
  #push:
   # branches: [ main ]
  #pull_request:
    #branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requests and nacl #安装requests模块
      run: |
        pip install requests
    - name: run api #api调用
      env: 
        #github的账号信息
        GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        GH_REPO: ${{ github.repository }}
        #以下是微软的账号信息
        APP_NUM: ${{ secrets.APP_NUM }} 
        #账号/应用1
        MS_TOKEN: ${{ secrets.MS_TOKEN }} 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        #发送信息
        url_bark: ${{ secrets.url_bark }}
        url_wechat: ${{ url_wechat }}
        url: ${{ url }}
        appToken: ${{ appToken }}
        UID: ${{ UID }}
        topicIds: ${{ topicIds }}
      run: |
        python index.py

    # Steps represent a sequence of tasks that will be executed as part of the job
